/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./components/ContextMenu/ContextMenu.vue')['default']
    GlobalAudio: typeof import('./components/Play/GlobalAudio.vue')['default']
    GlobalBackground: typeof import('./components/GlobalBackground.vue')['default']
    GlobalContextMenu: typeof import('./components/ContextMenu/GlobalContextMenu.vue')['default']
    HomeLayout: typeof import('./components/layout/HomeLayout.vue')['default']
    LyricDisplay: typeof import('./components/Play/Lyric/LyricDisplay.vue')['default']
    NBadge: typeof import('naive-ui')['NBadge']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    PlayMusic: typeof import('./components/Play/PlayMusic.vue')['default']
    Provider: typeof import('./components/layout/Provider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TButton: typeof import('tdesign-vue-next')['Button']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TitleBar: typeof import('./components/layout/TitleBar.vue')['default']
    TitleBarControls: typeof import('./components/TitleBarControls.vue')['default']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TProgress: typeof import('tdesign-vue-next')['Progress']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  }
}
