/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIChat: typeof import('./components/AI/AIChat.vue')['default']
    AIFloatBallSettings: typeof import('./components/Settings/AIFloatBallSettings.vue')['default']
    AudioEffectSettings: typeof import('./components/Settings/AudioEffectSettings.vue')['default']
    AudioOutputSettings: typeof import('./components/Settings/AudioOutputSettings.vue')['default']
    AudioVisualizer: typeof import('./components/Play/AudioVisualizer.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu/ContextMenu.vue')['default']
    DesktopLyricStyle: typeof import('./components/Settings/DesktopLyricStyle.vue')['default']
    DirectorySettings: typeof import('./components/Settings/DirectorySettings.vue')['default']
    DlnaDeviceSettings: typeof import('./components/Settings/DlnaDeviceSettings.vue')['default']
    EqualizerSettings: typeof import('./components/Settings/EqualizerSettings.vue')['default']
    GlobalAudio: typeof import('./components/Play/GlobalAudio.vue')['default']
    GlobalBackground: typeof import('./components/GlobalBackground.vue')['default']
    GlobalBackgroundSettings: typeof import('./components/Settings/GlobalBackgroundSettings.vue')['default']
    GlobalContextMenu: typeof import('./components/ContextMenu/GlobalContextMenu.vue')['default']
    HomeLayout: typeof import('./components/layout/HomeLayout.vue')['default']
    HotkeySettings: typeof import('./components/Settings/HotkeySettings.vue')['default']
    ImportPlaylist: typeof import('./components/ServicePlugin/ImportPlaylist.vue')['default']
    LyricDisplay: typeof import('./components/Play/Lyric/LyricDisplay.vue')['default']
    LyricFontSettings: typeof import('./components/Settings/LyricFontSettings.vue')['default']
    MusicCache: typeof import('./components/Settings/MusicCache.vue')['default']
    NBadge: typeof import('naive-ui')['NBadge']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    PlaylistSettings: typeof import('./components/Settings/PlaylistSettings.vue')['default']
    PlayMusic: typeof import('./components/Play/PlayMusic.vue')['default']
    PlaySettings: typeof import('./components/Play/PlaySettings.vue')['default']
    PluginSettings: typeof import('./components/Settings/PluginSettings.vue')['default']
    Provider: typeof import('./components/layout/Provider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsSearch: typeof import('./components/SettingsSearch.vue')['default']
    SkeletonLoader: typeof import('./components/SkeletonLoader.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TColorPicker: typeof import('tdesign-vue-next')['ColorPicker']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    ThemeSelector: typeof import('./components/ThemeSelector.vue')['default']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TitleBarControls: typeof import('./components/TitleBarControls.vue')['default']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TOption: typeof import('tdesign-vue-next')['Option']
    TProgress: typeof import('tdesign-vue-next')['Progress']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    UserCapsule: typeof import('./components/Auth/UserCapsule.vue')['default']
  }
}
